### ISSUE TITLE
Whose results are we agreeing with?

### ISSUE THREAD

**Issue by gregmacfarlane** [byu-transpolab/uvx_headways#4]
Reviewer 2:

> You cite agreement with Schultz et al (2020) but you don’t mention that Sheffield et al (2021) argued that the 0 min threshold offered the best improvement. The authors’ views on the reason for the discrepancy (or agreement) would be helpful.

**Comment by TranspoShef** [comment]
The commenter is mixed up. In this paper, we cite agreement with Schultz et al (2020) near the end of page 5 by referencing that Schultz et al (2020) found that the 2-min requesting threshold was favorable to the "always on" threshold. This is appropriately referencing the conclusions for UVX that were drawn by Schultz et al (2020). There is not a discrepancy between this and Sheffield et al (2021), which argues that the 0-min threshold offered the best improvement, because this finding only pertains to Route 217 and not UVX.

**Comment by gregmacfarlane** [comment]
Okay, so the distinction is in which route is considered. Why might a 2-minute threshold be better for a high-frequency service but a 0-minute threshold be better on a typical arterial bus route?

**Comment by TranspoShef** [comment]
We believe it is because any UVX bus can request TSP during the ON threshold, which means that early buses can receive TSP and become even earlier. Alternatively, the 0-min threshold for Route 217 prevents early buses from requesting TSP. Furthermore, Route 217 has a holding strategy whereby buses must wait at timepoints to prevent early departures, whereas UVX employs no holding strategy and operators do not try to maintain a schedule along the route.
